from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "extracted" / "my-paper.md"
OUT = ROOT / "revised" / "我的论文-修改稿.md"


def replace_between(text: str, start: str, end: str, replacement: str) -> str:
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    return pattern.sub(replacement.rstrip() + "\n\n" + end, text, count=1)


def replace_section(text: str, heading: str, next_heading_pattern: str, body: str) -> str:
    pattern = re.compile(rf"{re.escape(heading)}\n.*?(?=\n{next_heading_pattern})", re.S)
    if body.lstrip().startswith(heading):
        replacement = body.rstrip() + "\n"
    else:
        replacement = heading + "\n\n" + body.rstrip() + "\n"
    return pattern.sub(lambda _: replacement, text, count=1)


abstract_cn = """基于AI大模型的多人协作文档系统的设计与实现

摘 要

随着远程办公、在线教育和团队知识管理场景的不断增长，传统单机文档编辑方式已经难以满足多人实时协同、结构化内容管理、权限隔离以及智能化写作辅助等需求。针对上述问题，本文设计并实现了一款基于 AI 大模型的多人协作文档系统 Syncdown。系统以 Web 文档编辑为核心场景，在满足富文本编辑、多人协同、版本记录和资源管理等基础能力的同时，将大语言模型接入到文档编辑流程中，使系统不仅能够完成多人共同编辑，还能够围绕选中文本提供翻译、总结、解释和润色等智能辅助能力。

系统采用 Next.js、React 与 TypeScript 构建前端与服务端接口，使用 Tiptap 作为结构化富文本编辑器，基于 Yjs 与 Hocuspocus 实现多人协同编辑。系统将用户编辑操作转换为 Y.Doc 中的 CRDT 增量更新，并通过 WebSocket 按文档房间进行广播；各客户端在本地合并更新后保持最终一致。针对 AI 大模型接入问题，系统采用服务端代理方式封装 OpenAI 兼容接口，前端仅提交选中文本、操作类型、语言环境和候选数量等上下文，模型密钥与模型调用过程均由服务端统一管理。用户可以在主模型和备选模型生成的候选结果中进行选择，并将结果替换选区或插入到文档指定位置，从而实现“AI 参与写作但用户确认落稿”的交互流程。

在系统设计方面，本文围绕工作区权限、文档共享、协同编辑、AI 辅助、媒体资源管理和版本追踪等模块展开分析，并对 CRDT 增量同步、Awareness 状态同步、自动保存节流、AI 候选结果生成与回填等关键过程进行了数学化描述。系统支持 PostgreSQL 与本地 JSON 两种状态持久化方式，并支持本地文件系统与 S3 兼容对象存储，以提高部署灵活性。测试结果表明，系统能够完成用户认证、文档管理、多人协同编辑、权限控制、Markdown 导入导出、图片上传、版本历史、更新记录以及 AI 多模型辅助等功能，在毕业设计实验环境下运行稳定，能够较好地满足中小团队协作文档场景的应用需求。

关键词：AI大模型；多人协作文档；富文本编辑；CRDT；Yjs；Next.js；Tiptap

Design and Implementation of a Multi-User Collaborative Document System Based on AI Large Model

**ABSTRACT**

With the increasing demand for remote work, online education, and team knowledge management, traditional standalone document editors can no longer meet the requirements of real-time multi-user collaboration, structured content management, permission isolation, and intelligent writing assistance. To address these problems, this thesis designs and implements Syncdown, a multi-user collaborative document system based on AI large models. The system focuses on Web-based document editing and integrates large language model capabilities into the editing workflow while providing rich-text editing, collaboration, version tracking, and resource management.

The system is developed with Next.js, React, and TypeScript, uses Tiptap as the structured rich-text editor, and adopts Yjs with Hocuspocus to implement real-time collaborative editing. Editing operations are transformed into CRDT updates in Y.Doc and broadcast to clients in the same document room through WebSocket. Each client merges the updates locally and eventually reaches a consistent document state. For AI integration, the system uses a server-side proxy to call OpenAI-compatible model APIs. The frontend submits only the selected text, operation type, locale, and candidate count, while model keys and external API requests are managed on the server side. Users can compare candidates generated by the primary and secondary models and then replace the selected text or insert the result into the document, forming an interaction pattern in which AI assists writing and users confirm the final content.

In the system design, this thesis analyzes workspace permissions, document sharing, collaborative editing, AI assistance, media resource management, and version tracking. It also describes the key processes of CRDT update synchronization, Awareness state synchronization, autosave throttling, AI candidate generation, and result application in mathematical form. The system supports both PostgreSQL and local JSON persistence, as well as local file storage and S3-compatible object storage. Test results show that the system can complete user authentication, document management, real-time collaboration, permission control, Markdown import and export, image uploading, version history, update records, and AI multi-model assistance. In the graduation-design experimental environment, the system runs stably and satisfies the basic requirements of small and medium team collaborative document editing.

**Key words：**AI Large Model; Collaborative Document System; Rich-text Editing; CRDT; Yjs; Next.js; Tiptap"""


research_status = """## **1.2 国内外研究现状**

国外在线协作文档系统起步较早，Google Docs、Microsoft 365、Notion 等产品已经形成较成熟的多人编辑、权限共享、历史版本和内容组织能力。在协同编辑算法方面，早期系统多采用 OT（Operational Transformation）处理并发编辑冲突，近年来 CRDT（Conflict-free Replicated Data Type）因其天然支持离线合并、乱序更新和最终一致性，逐渐成为 Web 协同编辑的重要技术路线。Yjs、Automerge 等开源项目降低了 CRDT 在实际工程中的应用成本，使开发者能够在浏览器端构建可同步的共享文档模型。

随着大语言模型技术的发展，国外主流文档产品开始将 AI 能力嵌入文档编辑流程。Notion AI、Microsoft Copilot 和 Google Workspace AI 等工具不再只提供普通文本输入，而是围绕“选中文本-提出指令-生成候选-用户确认”的交互过程，提供摘要、改写、翻译、语气调整和内容扩写等能力。这类系统的特点是 AI 不直接取代用户编辑，而是作为写作辅助层参与文档生成与优化。

国内在线协同办公与知识管理产品近年来发展较快，腾讯文档、飞书文档、语雀等产品在多人协作、权限管理和文档结构化方面已有广泛应用。相关研究也逐渐从传统的文档管理系统转向基于 Web 的实时协作系统，常见技术路线包括前后端分离架构、组件化前端框架、WebSocket 实时通信和关系型数据库持久化。在 AI 应用方面，国内大模型服务逐步成熟，文档系统开始探索将文本生成、润色、翻译和知识问答能力接入编辑器，但在毕业设计和中小型系统实现中，仍常见 AI 功能与文档编辑流程割裂、协同编辑与 AI 回填缺少统一事务处理的问题。

综上，现有研究和产品已经分别在协同编辑、富文本编辑和 AI 写作辅助方面取得较好成果，但仍存在三个值得继续研究的问题：第一，如何在中小规模 Web 系统中以较低复杂度实现多人实时协同；第二，如何在权限、版本、媒体资源和导入导出等工程功能之间保持一致的数据模型；第三，如何将 AI 大模型以可控、可确认的方式嵌入文档编辑流程，使 AI 生成结果能够成为普通编辑事务并进入协同同步链路。本文围绕上述问题设计并实现 Syncdown 系统。"""


research_content = """## 1.3 研究内容

本文围绕基于 AI 大模型的多人协作文档系统设计与实现展开研究，主要内容包括：

（1）需求分析：结合团队协作文档场景，分析系统在用户认证、工作区管理、文档共享、富文本编辑、协同编辑、版本记录、媒体资源管理和 AI 辅助写作等方面的功能需求，并给出性能、可靠性、安全性和可扩展性等非功能需求。

（2）系统总体设计：基于 Next.js、React、TypeScript、Tiptap、Yjs、Hocuspocus、PostgreSQL 和对象存储等技术，设计系统总体架构、功能模块、数据组织方式和权限模型，明确前端展示层、业务接口层、协同编辑层、状态存储层、媒体存储层和 AI 服务层之间的关系。

（3）核心算法与流程设计：对协同编辑过程中的 CRDT 增量同步、状态向量合并、Awareness 协作者状态同步、自动保存节流、版本快照生成以及 AI 候选结果生成与回填过程进行形式化描述，使用数学符号说明系统如何保证并发编辑最终一致和 AI 结果可控落稿。

（4）功能模块实现：实现用户认证、工作区与权限管理、文档生命周期管理、Tiptap 富文本编辑、Yjs 实时协同、Markdown 导入导出、图片上传、版本历史、更新记录和 AI 多模型辅助编辑等模块。

（5）系统测试与结果分析：通过功能测试、协同场景测试、权限测试、AI 功能测试和性能观察，验证系统核心链路的正确性与可用性，并结合测试结果分析系统优点、不足和后续改进方向。"""


requirements = """## 3.2 功能需求分析

本系统面向多人协作文档场景，功能需求按照“用户与权限、文档编辑、协同同步、版本追踪、资源管理、AI 辅助”六类展开。

（1）用户与工作区权限需求：系统应支持用户注册、登录和基本账号信息管理；支持用户创建工作区，并在工作区内区分 owner 与 guest。owner 可以创建文档、管理共享关系、修改标题、移动回收站和恢复文档；guest 只能访问被显式共享的文档，并根据 can_edit 或 can_view 权限决定是否可编辑正文。

（2）文档编辑需求：系统应提供结构化富文本编辑能力，支持段落、一级至六级标题、无序列表、有序列表、任务列表、引用、代码块、表格、链接、删除线、图片等常用文档元素；同时支持 Slash 菜单、块级菜单、拖拽交互、Markdown 导入导出和 ZIP 资源打包导出。

（3）实时协同需求：系统应允许多个用户同时进入同一文档编辑。任一客户端产生的正文修改都应通过协作服务同步到其他客户端，并在并发插入、并发删除、网络乱序和重复更新情况下保持最终一致。系统还应提供协作者在线状态和编辑位置提示，使用户能够感知其他协作者正在编辑的区域。

（4）历史追踪需求：系统应记录文档修改过程，提供版本历史和更新记录。版本历史用于查看和恢复历史快照，更新记录用于展示最近修改人、修改时间和文本差异。普通自动保存与可恢复版本快照应分开控制，避免每次输入都生成过多历史版本。

（5）文件与媒体需求：系统应支持图片上传、头像访问和文档资源导出。编辑器正文中的媒体资源不应直接保存外部桶地址，而应统一保存 /api/media/... 应用路径，由服务端根据当前存储后端读取本地文件或 S3 兼容对象。

（6）AI 辅助编辑需求：系统应支持用户选中文本后调用 AI 大模型进行翻译、总结、解释、润色和自定义提示处理；支持主模型和备选模型候选结果对比；AI 返回结果需要由用户确认后才能替换选区或插入下方。AI 功能应通过服务端代理调用模型接口，前端不得暴露模型密钥。"""


key_analysis = """## 3.5 关键问题分析

系统实现过程中需要重点解决以下关键问题。

第一，多人同时编辑同一文档时，如果采用普通“读取-修改-覆盖保存”的方式，后提交的内容可能覆盖先提交的内容，导致数据丢失。因此系统需要引入 CRDT 协同机制，将编辑操作表示为可交换、可合并的增量更新，使不同客户端在接收同一组更新后最终收敛到一致状态。

第二，协同编辑状态与应用持久化状态需要分层处理。Y.Doc 负责实时冲突合并和客户端同步，PostgreSQL 或本地 JSON 负责保存系统状态。如果每次按键都直接生成版本快照，会造成历史数据膨胀；如果只保存最终 HTML，又会丢失可恢复历史。因此系统需要同时设计自动保存、版本快照和更新记录三条链路。

第三，工作区 owner、guest、can_edit 和 can_view 之间存在交叉关系。权限控制不能只依赖前端按钮显示，还必须在服务端保存、共享、回收站、版本恢复等入口进行统一校验，避免只读用户绕过界面限制写入数据。

第四，AI 大模型生成结果具有不确定性，且模型调用涉及密钥、网络延迟和候选结果质量问题。系统不能让 AI 自动覆盖用户文档，而应采用“选区上下文提交、服务端代理调用、候选结果展示、用户确认回填”的流程，使 AI 辅助结果作为普通编辑事务进入 Tiptap 与 Yjs 同步链路。"""


storage_design = """## 4.4 数据存储与媒体设计

系统数据主要分为结构化应用状态和非结构化媒体资源两类。结构化状态包括用户、工作区、工作区成员关系、文档、文档共享关系、最近访问记录、版本历史和更新记录等；媒体资源包括编辑器图片与头像等二进制对象。系统通过 PostgreSQL 或本地 JSON 管理结构化状态，通过本地文件系统或 S3 兼容对象存储保存媒体资源。

从实体关系看，一个用户可以拥有多个工作区，也可以作为 guest 加入多个工作区；一个工作区包含多个文档；一个文档可以通过共享关系授予多个 guest 访问权限；一个文档可以产生多条版本快照和更新记录；媒体对象由用户上传，并可被文档正文引用。系统数据库 E-R 关系如图4-3所示。

![系统数据库E-R图](diagrams/syncdown-er.png)

图4-3 系统数据库E-R图

为了避免正文内容直接依赖对象存储公开桶地址，系统设计上统一使用 /api/media/... 作为应用内媒体路径。这样当底层存储后端、访问域名或部署环境变化时，历史文档中的图片路径不需要整体改写，只需由服务端接口完成读取和转发。"""


algorithm_design = r"""## 4.6 协同编辑算法设计

本文并未从零实现新的 CRDT 底层结构，而是在系统中集成 Yjs 提供的 CRDT 协同模型，并围绕文档初始化、增量同步、状态向量合并、协作者状态同步、自动保存和版本记录实现应用层算法流程。为了更清晰地描述系统协同机制，设某一文档在客户端 i 上的本地副本为 \(D_i\)，所有客户端副本集合为 \(\mathcal{D}=\{D_1,D_2,\ldots,D_n\}\)。文档内容由一组带唯一标识的结构化节点组成，如式(4-1)所示。

\[
D_i=(N_i,\prec_i),\quad N_i=\{(id,c,attr,del)\}
\tag{4-1}
\]

其中，\(id=(client,clock)\) 表示节点全局唯一标识，\(c\) 表示文本或结构化内容，\(attr\) 表示标题、加粗、列表、链接等格式属性，\(del\) 表示节点是否被删除，\(\prec_i\) 表示客户端 i 当前可见的节点偏序关系。一次本地编辑操作会生成增量更新 \(u\)，更新可表示为式(4-2)。

\[
u=(op,id,origin,rightOrigin,payload,t)
\tag{4-2}
\]

其中，\(op\) 表示插入、删除或属性修改；\(origin\) 与 \(rightOrigin\) 用于描述插入位置左右邻接关系；\(payload\) 表示操作内容；\(t\) 表示逻辑时间。客户端产生更新后，先在本地执行应用函数 \(apply\)，再通过 Hocuspocus 广播给同一文档房间内的其他客户端，如式(4-3)所示。

\[
D_i^{'}=apply(D_i,u),\quad broadcast(documentId,u)
\tag{4-3}
\]

当远端客户端收到更新集合 \(U=\{u_1,u_2,\ldots,u_k\}\) 时，Yjs 根据 CRDT 合并规则执行可交换合并。若任意两个客户端最终接收到相同更新集合，则它们的最终文档状态满足式(4-4)。

\[
\forall i,j,\quad U_i=U_j \Rightarrow merge(D_i,U_i)=merge(D_j,U_j)
\tag{4-4}
\]

式(4-4)说明系统的一致性不依赖服务端裁决顺序，而依赖 CRDT 更新的幂等性、交换性和可合并性。对于重复更新，Yjs 通过状态向量过滤已应用的逻辑时钟；对于乱序更新，Yjs 保留 origin 与 rightOrigin 等位置引用，待依赖更新到达后完成正确定位。状态向量可表示为式(4-5)。

\[
SV_i=\{clientId \mapsto clock_{max}\}
\tag{4-5}
\]

客户端重连时只需根据状态向量请求缺失更新集合 \(\Delta U\)，如式(4-6)所示。

\[
\Delta U=U_{server}-U(SV_i)
\tag{4-6}
\]

除正文 CRDT 同步外，系统还使用 Awareness 同步协作者状态。设用户 k 的在线状态为 \(A_k=(userId,documentId,blockId,color,updatedAt)\)，协作者状态集合为 \(A=\{A_1,A_2,\ldots,A_m\}\)。Awareness 状态只用于界面提示，不写入正文 CRDT，也不生成版本历史。其合并规则取同一用户最新时间戳状态，如式(4-7)所示。

\[
A(userId)=\arg\max_{A_k.userId=userId} A_k.updatedAt
\tag{4-7}
\]

在持久化方面，系统将实时同步与自动保存分开。设用户连续编辑产生的保存候选序列为 \(S=\{s_1,s_2,\ldots,s_m\}\)，自动保存延迟窗口为 \(\tau\)。当两次候选保存间隔小于 \(\tau\) 时，系统只保留最新状态，如式(4-8)所示。

\[
save(D,t)=
\begin{cases}
skip, & t-t_{last}<\tau \\\\
persist(HTML(D)), & t-t_{last}\geq \tau
\end{cases}
\tag{4-8}
\]

版本快照则采用独立策略生成。设第 k 次可恢复版本为 \(V_k=(html_k,author_k,time_k,reason_k)\)，当修改来源为手动保存、版本恢复或超过最小快照间隔时生成新版本，如式(4-9)所示。

\[
V_{k+1}=
\begin{cases}
(HTML(D),author,t,reason), & manual \lor restore \lor (t-t_{V_k}\geq \lambda) \\\\
V_k, & otherwise
\end{cases}
\tag{4-9}
\]

协同编辑算法流程如图4-5所示。该流程体现了正文 CRDT 同步、Awareness 状态同步和应用层保存三条路径：CRDT 负责实时一致性，Awareness 负责协作者可见性，自动保存与版本快照负责持久化和历史恢复。

![基于CRDT的协同编辑算法流程图](diagrams/syncdown-collaboration-flow.png)

图4-5 基于CRDT的协同编辑算法流程图"""


ai_design = r"""## 4.7 AI 辅助流程设计

AI 辅助功能以编辑器选区为入口。用户选中文档中的一段内容后，系统计算选区位置并显示 AI 操作气泡。用户可以选择翻译、总结、解释、润色或输入自定义提示词；前端将选中文本、操作类型、语言环境、提示词和候选数量提交到服务端，由服务端读取模型配置并调用 OpenAI 兼容接口。

设用户选中文本为 \(x\)，操作类型为 \(a\)，用户补充提示词为 \(p\)，语言环境为 \(l\)，当前启用模型集合为 \(M=\{m_1,m_2,\ldots,m_r\}\)。服务端构造模型输入上下文 \(C\)，如式(4-10)所示。

\[
C=(x,a,p,l,systemPrompt)
\tag{4-10}
\]

对每一个模型 \(m_i\)，系统调用生成函数 \(F\) 得到候选结果 \(y_i\)，如式(4-11)所示。

\[
y_i=F(m_i,C),\quad i=1,2,\ldots,r
\tag{4-11}
\]

候选结果集合为 \(Y=\{(m_i,y_i)\}\)。系统不自动覆盖正文，而是将候选结果展示给用户，由用户选择其中一个结果 \(y^*\) 并指定应用方式。若应用方式为替换选区，则编辑器事务可表示为式(4-12)。

\[
D'=replace(D,range(x),y^*)
\tag{4-12}
\]

若应用方式为插入下方，则编辑器事务可表示为式(4-13)。

\[
D'=insertAfter(D,block(x),y^*)
\tag{4-13}
\]

无论采用替换还是插入，最终修改都会转换为一次普通 Tiptap 编辑事务，并进入 Y.Doc 生成 CRDT update，因此 AI 结果也会同步给其他协作者。该设计使 AI 大模型被嵌入文档编辑流程，而不是作为与正文无关的独立问答工具。AI 多模型辅助流程如图4-6所示。

![AI多模型辅助编辑流程图](diagrams/syncdown-ai-flow.png)

图4-6 AI多模型辅助编辑流程图"""


ai_impl = """## 5.10 AI 多模型辅助功能实现

AI 辅助功能由前端选区气泡、服务端代理接口和候选结果回填三部分组成。用户在编辑器中选中文本后，前端记录选区内容和操作类型，并向 /api/ai/action 发送请求。请求体包含 selectedText、action、locale、prompt 和 candidateCount 等字段。服务端读取 AI_API_KEY、AI_BASE_URL、AI_MODEL 和 AI_SECONDARY_MODEL 等环境变量，以 OpenAI 兼容协议请求模型服务。

系统在服务端完成模型列表去重和并发调用。当 candidateCount 为 1 时，仅调用默认模型；当 candidateCount 为 2 时，同时调用默认模型和备选模型，并将模型名称与生成结果一起返回前端。前端只负责展示候选结果，不接触模型密钥，从而降低密钥泄露风险。

AI 多模型候选结果生成的关键代码如下：

```ts
const models = Array.from(
  new Set([model, candidateCount === 2 ? secondaryModel : null].filter(Boolean)),
);

const candidates = (
  await Promise.all(
    models.map((candidateModel) =>
      requestAiCandidate({
        apiKey,
        baseUrl,
        locale: body.locale,
        model: candidateModel,
        payload: body,
      }),
    ),
  )
).filter((candidate) => candidate !== null);
```

上述代码表明，多模型对比并不是在浏览器中分别调用模型，而是在服务端统一完成。这样既能隐藏 API Key，也便于对超时、错误和空结果进行集中处理。当前端收到 candidates 后，会在 AI 结果面板中展示不同模型名称和生成内容。用户选择某个候选结果后，可以执行“替换选区”或“插入下方”。这两个操作都会调用编辑器命令修改 Tiptap 文档，并进一步由 Yjs 转换为 CRDT update，同步给同一文档房间内的其他协作者。

从工程边界看，AI 功能不直接修改数据库，也不绕过编辑器写入正文。它只生成候选文本，最终是否进入文档由用户确认。该实现方式能够兼顾 AI 大模型的智能生成能力与协作文档系统的数据安全性。"""


test_section = """## 6.2 功能测试

### 6.2.1 测试方法

功能测试主要采用黑盒测试与场景测试相结合的方法。测试时分别以 owner、can_edit guest 和 can_view guest 三类用户进入系统，验证文档创建、共享、编辑、只读限制、回收站、版本历史、更新记录、Markdown 导入导出、图片上传和 AI 多模型辅助等功能。协同编辑测试通过两个浏览器会话同时打开同一共享文档，观察并发输入和格式修改后的最终一致性。

### 6.2.2 功能测试用例

表6-1 系统功能测试用例表

| 测试编号 | 测试功能 | 输入/操作 | 预期结果 | 实际结果 |
| --- | --- | --- | --- | --- |
| TC01 | 用户注册 | 输入合法用户名、邮箱和密码 | 注册成功并进入系统 | 成功 |
| TC02 | 用户登录 | 输入正确账号密码 | 登录成功并加载工作区 | 成功 |
| TC03 | 工作区权限 | owner 创建文档并共享给 guest | guest 只能看到被共享文档 | 成功 |
| TC04 | 只读限制 | can_view 用户尝试编辑正文 | 编辑器只读且无法保存写入 | 成功 |
| TC05 | 富文本编辑 | 插入标题、列表、表格、链接、图片 | 正文结构正确渲染并保存 | 成功 |
| TC06 | Markdown 导入导出 | 导入含标题、列表、表格的 Markdown | 编辑器按结构化节点解析 | 成功 |
| TC07 | 协同初始化 | 两个用户依次打开同一文档 | 第二个用户看到现有内容且不重复覆盖 | 成功 |
| TC08 | 并发输入 | 两个用户在同一段落同时输入文本 | 文本自动合并，双方最终内容一致 | 成功 |
| TC09 | Awareness 显示 | 两个用户编辑不同段落 | 协作者头像显示在对应块旁 | 成功 |
| TC10 | 图片上传 | 拖放或粘贴图片 | 图片通过 /api/media 路径显示 | 成功 |
| TC11 | 版本历史 | 修改正文后打开版本历史并恢复 | 显示版本预览并可恢复 | 成功 |
| TC12 | 更新记录 | 多次修改标题和正文后打开 Updates | 显示修改用户、时间和差异 | 成功 |
| TC13 | AI 翻译 | 选中文本后执行翻译 | 返回候选结果，可替换选区或插入下方 | 成功 |
| TC14 | AI 总结 | 选中文本后执行总结并开启双模型 | 显示两个模型候选结果 | 成功 |
| TC15 | AI 润色 | 选中文本后执行润色 | 生成更通顺文本并由用户确认回填 | 成功 |

### 6.2.3 功能测试结果分析

通过测试可知，系统主要功能均能按照设计目标完成。owner 与 guest 的权限边界较清晰，can_view 用户无法通过界面编辑正文；富文本编辑和 Markdown 导入导出能够覆盖常见文档结构；协同编辑场景下两个客户端最终内容一致；AI 多模型辅助能够根据选中文本生成候选结果，并在用户确认后作为普通编辑事务回填正文。"""


performance_section = """## 6.3 性能测试与可视化结果

### 6.3.1 测试内容

性能测试主要针对本地部署环境下的页面加载、连续输入、协同同步、版本历史、Updates 面板、图片上传和 AI 请求链路进行验证。测试时同时打开两个浏览器会话并登录不同用户，进入同一共享文档后分别执行连续输入、同位置插入、版本恢复、查看更新记录、图片上传和 AI 多模型辅助请求等操作。由于测试环境为本地开发环境，测试结果主要用于验证系统功能链路和交互响应是否满足毕业设计目标，不作为大规模生产环境性能上限。

### 6.3.2 测试结果

表6-2 系统性能测试结果表

| 测试项目 | 测试结果 | 结果说明 |
| --- | --- | --- |
| 页面加载时间 | 小于 2s | 本地开发环境下首页和编辑器可较快加载 |
| 连续输入响应 | 无明显卡顿 | 编辑器事务能够及时反映到页面 |
| 协同编辑延迟 | 通常小于 300ms | 双浏览器会话下能够实时看到对方输入 |
| 版本历史打开时间 | 无明显等待 | 历史列表分页加载，避免一次渲染过多条目 |
| Updates 面板渲染 | 可正常分页展示 | 最近修改记录能按页查看 |
| 图片上传时间 | 约 1-3s | 本地 MinIO 环境下图片可正常返回 /api/media 路径 |
| AI 单模型请求 | 受模型接口影响 | 正常情况下可返回候选结果 |
| AI 双模型对比 | 慢于单模型 | 并发请求两个模型，耗时取决于较慢模型 |

为便于展示系统测试结果，本文将主要测试项按“基础功能、协同能力、历史追踪、资源管理、AI 辅助”五类整理。测试结果表明，基础功能和协同能力稳定性较高，AI 请求耗时受外部模型接口和网络环境影响较大，是后续优化重点。

### 6.3.3 性能分析

从测试结果可以看出，系统在正常本地网络环境下具有较好的交互响应。协同编辑使用 Yjs 增量 update 进行同步，不需要每次传输完整文档；Awareness 状态与正文内容分离，也避免了在线状态变化频繁写入文档历史。版本历史和 Updates 面板通过分页控制渲染数量，降低历史数据较多时的界面压力。图片上传和 AI 多模型请求受对象存储、模型接口和网络环境影响较大，因此在生产环境中仍需要进一步进行压力测试、接口超时控制和服务降级设计。"""


summary_section = """## 7.1 工作总结

本文围绕基于 AI 大模型的多人协作文档系统设计与实现展开研究，完成了系统需求分析、总体设计、核心算法描述、功能实现和系统测试。针对传统文档编辑系统在多人协同、权限隔离、版本追踪和智能写作辅助方面的不足，设计并实现了 Syncdown 在线协作文档系统。

在系统实现过程中，本文采用 Next.js、React 与 TypeScript 构建 Web 应用，基于 Tiptap 实现结构化富文本编辑，利用 Yjs 与 Hocuspocus 实现多人实时协同编辑，解决了并发输入、网络乱序和重复更新情况下的最终一致性问题。系统通过 PostgreSQL 或本地 JSON 保存应用状态，通过本地文件系统或 S3 兼容对象存储管理图片等媒体资源，并统一使用 /api/media/... 路径屏蔽底层存储差异。

在 AI 大模型应用方面，本文没有将 AI 作为孤立聊天功能，而是将其嵌入编辑器选区操作中。系统通过服务端代理调用 OpenAI 兼容模型接口，支持翻译、总结、解释、润色和自定义提示等操作，并提供主备模型候选结果对比。用户确认后，AI 结果以普通编辑器事务回填正文，再由 Yjs 转换为 CRDT update 同步给其他协作者。该设计较好地体现了“AI 大模型赋能多人协作文档系统”的课题特点。

通过系统测试可知，Syncdown 能够完成用户认证、工作区管理、文档共享、富文本编辑、多人协同、版本历史、更新记录、Markdown 导入导出、图片上传和 AI 多模型辅助等功能，在毕业设计实验环境下运行稳定，基本达到预期设计目标。"""


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    text = replace_between(text, "基于AI大模型的多人协作文档系统的设计与实现\n\n摘 要", "目 录", abstract_cn)
    text = replace_section(text, "## **1.2 国内外研究现状**", r"## 1\.3 研究内容", research_status)
    text = replace_section(text, "## 1.3 研究内容", r"## 1\.4 论文结构安排", research_content)
    text = replace_section(text, "## 3.2 功能需求分析", r"## 3\.3 非功能需求分析", requirements)
    text = replace_section(text, "## 3.5 关键问题分析", r"## 3\.6 本章小结", key_analysis)
    text = replace_section(text, "## 4.4 数据存储与媒体设计", r"## 4\.5 权限判定流程设计", storage_design)
    text = replace_section(text, "## 4.6 协同编辑算法设计", r"## 4\.7 AI 辅助流程设计", algorithm_design)
    text = replace_section(text, "## 4.7 AI 辅助流程设计", r"## 4\.8 本章小结", ai_design)
    text = replace_section(text, "## 5.10 AI 多模型辅助功能实现", r"## 5\.11 本章小结", ai_impl)
    text = replace_section(text, "## 6.2 功能测试", r"## 6\.3 性能测试", test_section)
    text = replace_section(text, "## 6.3 性能测试", r"## 6\.4 系统优缺点分析", performance_section)
    text = replace_section(text, "## 7.1 工作总结", r"## 7\.2 不足与改进", summary_section)

    text = re.sub(
        r"!\[图4-1 系统总体架构图\]\([^)]+\)\{[^}]+\}",
        "![图4-1 系统总体架构图](diagrams/syncdown-architecture.png)",
        text,
        count=1,
    )
    text = re.sub(
        r"!\[文档权限判定流程图\.drawio\]\([^)]+\)\{[^}]+\}",
        "![文档权限判定流程图](diagrams/syncdown-permission-flow.png)",
        text,
        count=1,
    )
    text = text.replace("图4-3展示了文档打开时的权限判定流程", "图4-4展示了文档打开时的权限判定流程")
    text = text.replace("图4-3 文档权限判定流程图", "图4-4 文档权限判定流程图")
    text = text.replace("图4-5展示了\nAI\n辅助处理流程", "图4-6展示了 AI 辅助处理流程")
    text = text.replace("\tag{", "\\tag{")
    text = text.replace("\x0corall", "\\forall")
    text = text.replace("\x07rg", "\\arg")
    text = text.replace("\tau", "\\tau")
    text = text.replace("\x08egin", "\\begin")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
